/**
 * Render the dependency matrix — package × repo × declared version against the §3
 * baseline — to `docs/measurements/deps.md`.
 *
 *     bun tools/inventory/deps.ts                  # read sibling checkouts from disk
 *     bun tools/inventory/deps.ts --remote         # read each repo's default branch on GitHub (CI)
 *     bun tools/inventory/deps.ts --out -          # print instead of writing the file
 *     bun tools/inventory/deps.ts --strict --repo val
 *                                                  # exit 1 if that repo has undocumented deviations
 *
 * The repo list is `concepts.toml`'s; the baseline is `baseline.toml`. Only `dependencies`
 * and `devDependencies` are classified: a library's peer range is meant to be wide, and is
 * not what an app installs.
 */

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { parseArgs } from "node:util";

import { gitSha, labelOf, loadInventory, type Inventory, type Repo } from "./inventory";
import { DEVIATIONS, classify, type Baseline, type Status } from "./versions";

const HERE = dirname(new URL(import.meta.url).pathname);
const DEFAULT_OUT = resolve(HERE, "../../docs/measurements/deps.md");

interface Declared {
  spec: string;
  status: Status;
  exception?: string;
}

interface RepoDeps {
  id: string;
  sha: string;
  /** package name → what the repo declares (first manifest that names it wins). */
  deps: Map<string, Declared>;
  missing: string[];
}

const MARK: Record<Status, string> = {
  ok: "✓",
  patch: "✓",
  behind: "↓",
  ahead: "↑",
  "not-exact": "≠",
  replaced: "✗",
  untracked: "",
  unparsed: "",
};

function expandHome(path: string): string {
  return path.startsWith("~/") ? join(homedir(), path.slice(2)) : path;
}

function manifestsOf(repo: Repo): string[] {
  return (repo.manifests ?? ["package.json"]).map((m) => (repo.frontend === "." ? m : `${repo.frontend}/${m}`));
}

type Manifest = { dependencies?: Record<string, string>; devDependencies?: Record<string, string> };

async function readLocal(repo: Repo): Promise<{ sha: string; manifests: (Manifest | null)[] }> {
  const root = expandHome(repo.root);
  return {
    sha: gitSha(root),
    manifests: manifestsOf(repo).map((m) => {
      const path = join(root, m);
      return existsSync(path) ? (JSON.parse(readFileSync(path, "utf8")) as Manifest) : null;
    }),
  };
}

async function readRemote(repo: Repo): Promise<{ sha: string; manifests: (Manifest | null)[] }> {
  const headers: Record<string, string> = { accept: "application/vnd.github+json" };
  if (process.env.GITHUB_TOKEN) headers.authorization = `Bearer ${process.env.GITHUB_TOKEN}`;
  const commit = await fetch(`https://api.github.com/repos/${repo.github}/commits/HEAD`, { headers });
  if (!commit.ok) throw new Error(`${repo.github}: HEAD lookup failed (${commit.status})`);
  const sha = ((await commit.json()) as { sha: string }).sha;
  const manifests = await Promise.all(
    manifestsOf(repo).map(async (m) => {
      const res = await fetch(`https://raw.githubusercontent.com/${repo.github}/${sha}/${m}`);
      return res.ok ? ((await res.json()) as Manifest) : null;
    }),
  );
  return { sha: sha.slice(0, 10), manifests };
}

export function collect(
  id: string,
  sha: string,
  manifests: (Manifest | null)[],
  names: string[],
  baseline: Baseline,
): RepoDeps {
  const deps = new Map<string, Declared>();
  const missing: string[] = [];
  manifests.forEach((manifest, i) => {
    if (!manifest) {
      missing.push(names[i]!);
      return;
    }
    for (const [name, spec] of Object.entries({ ...manifest.devDependencies, ...manifest.dependencies })) {
      if (deps.has(name)) continue;
      const status = classify(name, spec, baseline);
      const exception = baseline.exceptions[`${id}.${name}`];
      deps.set(name, { spec, status, ...(exception ? { exception } : {}) });
    }
  });
  return { id, sha, deps, missing };
}

/** Deviations that are not covered by a documented exception. */
export function undocumented(repo: RepoDeps): [string, Declared][] {
  return [...repo.deps].filter(([, d]) => DEVIATIONS.has(d.status) && !d.exception);
}

function render(inventory: Inventory, baseline: Baseline, repos: RepoDeps[], source: string): string {
  const tracked = [...Object.keys(baseline.packages), ...Object.keys(baseline.replaced)];
  const declared = tracked.filter((name) => repos.some((r) => r.deps.has(name)));
  const lines: string[] = [];
  lines.push("# Dependency matrix");
  lines.push("");
  lines.push(
    "Generated by `bun tools/inventory/deps.ts` from `tools/inventory/baseline.toml` (PLAN.md §3, ADR-0002) — edit the TOML, not this file. " +
      `Source: ${source}.`,
  );
  lines.push("");
  lines.push(
    "Declared `dependencies`/`devDependencies`, read from the range's lower bound. " +
      "✓ at baseline (patch lag allowed) · ↓ behind · ↑ ahead of the baseline · ≠ must be an exact pin · ✗ replaced package · *(e)* documented exception.",
  );
  lines.push("");

  lines.push("## Deviations per repo");
  lines.push("");
  lines.push("| Repo | Commit | Undocumented deviations | Documented exceptions |");
  lines.push("|---|---|---|---|");
  for (const repo of repos) {
    const exceptions = [...repo.deps.values()].filter((d) => d.exception && DEVIATIONS.has(d.status)).length;
    const missing = repo.missing.length ? ` (missing: ${repo.missing.join(", ")})` : "";
    lines.push(
      `| ${labelOf(inventory, repo.id)} | \`${repo.sha}\` | ${undocumented(repo).length}${missing} | ${exceptions} |`,
    );
  }
  lines.push("");

  lines.push("## Matrix");
  lines.push("");
  const header = ["Package", "Baseline", ...repos.map((r) => labelOf(inventory, r.id))];
  lines.push(`| ${header.join(" | ")} |`);
  lines.push(`|${header.map(() => "---").join("|")}|`);
  for (const name of declared) {
    const entry = baseline.packages[name];
    const want = entry ? `${entry.exact ? "=" : ""}${entry.version}` : "✗ → " + baseline.replaced[name];
    const cells = repos.map((r) => {
      const d = r.deps.get(name);
      if (!d) return "";
      return `\`${d.spec}\` ${MARK[d.status]}${d.exception ? " *(e)*" : ""}`.trim();
    });
    lines.push(`| \`${name}\` | ${want} | ${cells.join(" | ")} |`);
  }
  lines.push("");

  lines.push("## Deviation details");
  lines.push("");
  for (const repo of repos) {
    const devs = [...repo.deps].filter(([, d]) => DEVIATIONS.has(d.status));
    if (!devs.length) continue;
    lines.push(`### ${labelOf(inventory, repo.id)}`);
    lines.push("");
    for (const [name, d] of devs) {
      const entry = baseline.packages[name];
      const why =
        d.status === "replaced"
          ? `replace with ${baseline.replaced[name]}`
          : `baseline ${entry!.exact ? "exactly " : ""}${entry!.version}${entry!.note ? ` — ${entry!.note}` : ""}`;
      lines.push(`- \`${name}\` \`${d.spec}\` — **${d.status}**; ${why}${d.exception ? ` · exception: ${d.exception}` : ""}`);
    }
    lines.push("");
  }
  return lines.join("\n");
}

async function main() {
  const { values } = parseArgs({
    options: {
      remote: { type: "boolean", default: false },
      strict: { type: "boolean", default: false },
      repo: { type: "string", multiple: true },
      out: { type: "string", default: DEFAULT_OUT },
    },
  });
  const inventory = loadInventory();
  const baseline = Bun.TOML.parse(readFileSync(join(HERE, "baseline.toml"), "utf8")) as Baseline;
  baseline.exceptions ??= {};
  const ids = values.repo?.length ? values.repo : Object.keys(inventory.repos);
  for (const id of ids) if (!inventory.repos[id]) throw new Error(`unknown repo "${id}"`);

  const repos = await Promise.all(
    ids.map(async (id) => {
      const repo = inventory.repos[id]!;
      const { sha, manifests } = await (values.remote ? readRemote(repo) : readLocal(repo));
      return collect(id, sha, manifests, manifestsOf(repo), baseline);
    }),
  );

  const report = render(inventory, baseline, repos, values.remote ? "each repo's default branch on GitHub" : "local checkouts");
  if (values.out === "-") console.log(report);
  else {
    writeFileSync(values.out!, report);
    console.error(`wrote ${values.out}`);
  }

  if (values.strict) {
    const failing = repos.filter((r) => undocumented(r).length > 0);
    for (const r of failing) {
      console.error(`${labelOf(inventory, r.id)}: ${undocumented(r).length} undocumented deviation(s)`);
      for (const [name, d] of undocumented(r)) console.error(`  ${name} ${d.spec} (${d.status})`);
    }
    if (failing.length) process.exit(1);
  }
}

if (import.meta.main) await main();
