/**
 * Render the concept matrix (`concepts.toml`) to `docs/measurements/concept-matrix.md`.
 *
 *     bun tools/inventory/matrix.ts            # write the report
 *     bun tools/inventory/matrix.ts --check    # only validate: every listed path exists
 *
 * It reads sibling repositories from disk (the `root` of each repo in `concepts.toml`), so
 * it runs on a machine that has them checked out. A listed path that does not exist is an
 * error, never a warning: the matrix is only worth reading while it is exactly true, and a
 * moved file is the usual way it stops being so.
 *
 * The output is deterministic for a given set of checkouts — no timestamps; the commit SHA
 * of every repo is recorded instead, which is what "when was this measured" actually means.
 */

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join, resolve } from "node:path";

import { gitSha, labelOf, loadInventory, type Concept, type Inventory } from "./inventory";

const HERE = dirname(new URL(import.meta.url).pathname);
const REPO_ROOT = resolve(HERE, "../..");
const OUT = join(REPO_ROOT, "docs/measurements/concept-matrix.md");
const SURVEY = join(HERE, "github-react-repos.txt");

const LAYERS = ["ui", "forms", "charts", "stage2d", "overlays", "three"] as const;

function expandHome(path: string): string {
  return path.startsWith("~/") ? join(homedir(), path.slice(2)) : path;
}

/** Every listed path that does not exist on disk, as `repo: path`. */
export function missingPaths(inventory: Inventory): string[] {
  const missing: string[] = [];
  for (const [id, concept] of Object.entries(inventory.concepts)) {
    for (const [repo, paths] of Object.entries(concept.impl ?? {})) {
      const meta = inventory.repos[repo];
      if (!meta) {
        missing.push(`${id}: unknown repo "${repo}"`);
        continue;
      }
      const base = join(expandHome(meta.root), meta.frontend);
      for (const path of paths) {
        if (!existsSync(join(base, path))) missing.push(`${id} · ${repo}: ${path}`);
      }
    }
    for (const repo of [...Object.keys(concept.uses ?? {}), ...Object.keys(concept.note ?? {})]) {
      if (!inventory.repos[repo]) missing.push(`${id}: unknown repo "${repo}"`);
    }
  }
  return missing;
}

/** One table cell: local file count, shared package, a note, or nothing. */
function cell(concept: Concept, repo: string): string {
  const local = concept.impl?.[repo]?.length ?? 0;
  const uses = concept.uses?.[repo];
  const parts: string[] = [];
  if (local > 0) parts.push(`**${local}**`);
  if (uses) parts.push("◆");
  if (parts.length === 0 && concept.note?.[repo]) parts.push("·");
  return parts.length ? parts.join(" ") : "";
}

/** How many repos carry their own implementation of a concept (lab-ui included). */
export function implementationCount(concept: Concept): number {
  return Object.values(concept.impl ?? {}).filter((paths) => paths.length > 0).length;
}

function render(inventory: Inventory): string {
  const repoIds = Object.keys(inventory.repos);
  const inPlan = repoIds.filter((id) => inventory.repos[id]!.in_plan);
  const extra = repoIds.filter((id) => !inventory.repos[id]!.in_plan);
  const ordered = [...inPlan, ...extra];

  const lines: string[] = [];
  lines.push("# Concept matrix");
  lines.push("");
  lines.push(
    "Generated by `bun tools/inventory/matrix.ts` from `tools/inventory/concepts.toml` — edit the TOML, not this file.",
  );
  lines.push("");
  lines.push(
    "Cells: **n** = files in that repo implementing the concept locally · ◆ = uses a shared package · · = see notes · blank = absent. " +
      "*Impl.* counts repos with a local implementation (lab-ui included); PLAN L9-1 ends at 1 per concept.",
  );
  lines.push("");

  const header = ["Concept", "Layer", "Impl.", ...ordered.map((id) => labelOf(inventory, id))];
  lines.push(`| ${header.join(" | ")} |`);
  lines.push(`|${header.map(() => "---").join("|")}|`);
  const concepts = sortedConcepts(inventory);
  for (const [id, concept] of concepts) {
    const row = [
      `[${concept.label}](#${id})`,
      concept.layer,
      String(implementationCount(concept)),
      ...ordered.map((repo) => cell(concept, repo)),
    ];
    lines.push(`| ${row.join(" | ")} |`);
  }
  lines.push("");
  lines.push(`Columns from *${labelOf(inventory, extra[0] ?? "")}* onward are outside PLAN.md §0 (mapped, not yet in scope).`);
  lines.push("");

  lines.push("## Summary by layer");
  lines.push("");
  lines.push("| Layer | Concepts | Local implementations | Concepts with >1 implementation |");
  lines.push("|---|---|---|---|");
  for (const layer of LAYERS) {
    const inLayer = concepts.filter(([, c]) => c.layer === layer);
    const total = inLayer.reduce((n, [, c]) => n + implementationCount(c), 0);
    const duplicated = inLayer.filter(([, c]) => implementationCount(c) > 1).length;
    lines.push(`| ${layer} | ${inLayer.length} | ${total} | ${duplicated} |`);
  }
  lines.push("");

  lines.push("## Concepts");
  lines.push("");
  for (const [id, concept] of concepts) {
    lines.push(`<a id="${id}"></a>`);
    lines.push("");
    lines.push(`### ${concept.label}`);
    lines.push("");
    for (const repo of ordered) {
      const paths = concept.impl?.[repo] ?? [];
      const uses = concept.uses?.[repo];
      const note = concept.note?.[repo];
      if (!paths.length && !uses && !note) continue;
      const bits: string[] = [];
      if (paths.length) bits.push(paths.map((p) => `\`${p}\``).join(", "));
      if (uses) bits.push(`uses \`${uses}\``);
      if (note) bits.push(`_${note}_`);
      lines.push(`- **${labelOf(inventory, repo)}**: ${bits.join(" · ")}`);
    }
    lines.push("");
  }

  lines.push("## Repositories measured");
  lines.push("");
  lines.push("| Repo | Frontend | Commit | In PLAN §0 |");
  lines.push("|---|---|---|---|");
  for (const id of ordered) {
    const meta = inventory.repos[id]!;
    lines.push(
      `| [${labelOf(inventory, id)}](https://github.com/${meta.github}) | \`${meta.frontend}\` | \`${gitSha(expandHome(meta.root))}\` | ${meta.in_plan ? "yes" : "no"} |`,
    );
  }
  lines.push("");

  lines.push("## React frontends on GitHub not in PLAN §0");
  lines.push("");
  lines.push(
    "From `tools/inventory/github-react-repos.sh` (`gh search code` for `package.json` files naming `react`). " +
      "Frontends that are mapped above are marked; the rest are reported only.",
  );
  lines.push("");
  const mapped = new Set(
    repoIds.map((id) => {
      const meta = inventory.repos[id]!;
      return `${meta.github} ${meta.frontend === "." ? "" : `${meta.frontend}/`}package.json`;
    }),
  );
  const survey = existsSync(SURVEY)
    ? readFileSync(SURVEY, "utf8")
        .split("\n")
        .map((l) => l.trim())
        .filter((l) => l && !l.startsWith("#"))
    : [];
  for (const entry of survey) {
    if (mapped.has(entry) && inventory.repos[repoFor(inventory, entry)]?.in_plan) continue;
    const tag = mapped.has(entry) ? " — mapped" : "";
    lines.push(`- \`${entry}\`${tag}`);
  }
  lines.push("");
  return lines.join("\n");
}

function repoFor(inventory: Inventory, entry: string): string {
  for (const [id, meta] of Object.entries(inventory.repos)) {
    const key = `${meta.github} ${meta.frontend === "." ? "" : `${meta.frontend}/`}package.json`;
    if (key === entry) return id;
  }
  return "";
}

function sortedConcepts(inventory: Inventory): [string, Concept][] {
  // Layer order, then the order written in the TOML (which groups related concepts).
  return Object.entries(inventory.concepts).sort(
    ([, a], [, b]) => LAYERS.indexOf(a.layer as (typeof LAYERS)[number]) - LAYERS.indexOf(b.layer as (typeof LAYERS)[number]),
  );
}

if (import.meta.main) {
  const inventory = loadInventory();
  const missing = missingPaths(inventory);
  if (missing.length) {
    console.error(`concepts.toml lists ${missing.length} path(s) that do not exist:`);
    for (const m of missing) console.error(`  ${m}`);
    process.exit(1);
  }
  if (process.argv.includes("--check")) {
    console.log("concepts.toml: every listed path exists.");
  } else {
    writeFileSync(OUT, render(inventory));
    console.log(`wrote ${OUT}`);
  }
}
