/**
 * Vendors the IBM Plex files `@vitavision/ui/fonts.css` serves (ADR-0003) into
 * `packages/ui/src/fonts/`, and writes that stylesheet.
 *
 * - IBM Plex Sans: the variable `wght` build from fontsource, latin and latin-ext subsets.
 * - IBM Plex Mono 400 and 500: IBM's own split files (Latin1/2/3 and Pi). fontsource's build
 *   drops the `zero` feature, so there `slashed-zero` falls back to a dotted zero; IBM's
 *   files keep it.
 *
 * The unicode ranges are copied from each source's own CSS, so a browser fetches only the
 * files a page's text needs. Run after bumping either source package, then commit the diff:
 *
 *   bun tools/visual-language/vendor-fonts.ts
 */

import { copyFileSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = join(import.meta.dir, "..", "..");
const OUT = join(ROOT, "packages/ui/src/fonts");
const SANS = join(ROOT, "node_modules/@fontsource-variable/ibm-plex-sans");
const MONO = join(ROOT, "node_modules/@ibm/plex-mono");

const SANS_SUBSETS = ["latin-ext", "latin"];
const MONO_WEIGHTS: Record<number, string> = { 400: "Regular", 500: "Medium" };
const MONO_SPLITS = ["Latin1", "Latin2", "Latin3", "Pi"];

interface Face {
  family: string;
  weight: string;
  file: string;
  format: string;
  unicodeRange: string;
}

/** The `@font-face` blocks of a stylesheet, as raw text. */
function blocks(css: string): string[] {
  return [...css.matchAll(/@font-face\s*\{[^}]*\}/g)].map(([block]) => block);
}

function field(block: string, name: string): string {
  const match = new RegExp(`${name}:\\s*([^;]+);`).exec(block);
  if (!match?.[1]) throw new Error(`no ${name} in ${block}`);
  return match[1].trim();
}

function sansFaces(): Face[] {
  const css = readFileSync(join(SANS, "index.css"), "utf8");
  return SANS_SUBSETS.map((subset) => {
    const file = `ibm-plex-sans-${subset}-wght-normal.woff2`;
    const block = blocks(css).find((b) => b.includes(`/${file}`));
    if (!block) throw new Error(`fontsource has no ${file}`);
    return { family: "IBM Plex Sans Variable", weight: "100 700", file, format: "woff2-variations", unicodeRange: field(block, "unicode-range") };
  });
}

function monoFaces(): Face[] {
  const css = readFileSync(join(MONO, "css/ibm-plex-mono-all.css"), "utf8");
  return Object.entries(MONO_WEIGHTS).flatMap(([weight, style]) =>
    MONO_SPLITS.map((split) => {
      const file = `IBMPlexMono-${style}-${split}.woff2`;
      const block = blocks(css).find((b) => b.includes(`split/woff2/${file}`));
      if (!block) throw new Error(`@ibm/plex-mono has no ${file}`);
      return { family: "IBM Plex Mono", weight, file, format: "woff2", unicodeRange: field(block, "unicode-range") };
    }),
  );
}

function source(face: Face): string {
  return face.family === "IBM Plex Mono" ? join(MONO, "fonts/split/woff2", face.file) : join(SANS, "files", face.file);
}

const faces = [...sansFaces(), ...monoFaces()];
const sansVersion = (JSON.parse(readFileSync(join(SANS, "package.json"), "utf8")) as { version: string }).version;
const monoVersion = (JSON.parse(readFileSync(join(MONO, "package.json"), "utf8")) as { version: string }).version;

rmSync(OUT, { recursive: true, force: true });
mkdirSync(OUT, { recursive: true });
for (const face of faces) copyFileSync(source(face), join(OUT, face.file));
copyFileSync(join(SANS, "LICENSE"), join(OUT, "LICENSE-IBM-Plex-Sans.txt"));
copyFileSync(join(MONO, "LICENSE.txt"), join(OUT, "LICENSE-IBM-Plex-Mono.txt"));

const css = `/*
 * IBM Plex for the @vitavision packages: import once, next to styles.css.
 *
 *   @import "@vitavision/ui/fonts.css";
 *
 * Generated by tools/visual-language/vendor-fonts.ts — do not edit by hand.
 * IBM Plex Sans ${sansVersion} (@fontsource-variable/ibm-plex-sans) and IBM Plex Mono ${monoVersion}
 * (@ibm/plex-mono, whose files keep the \`zero\` feature), under the SIL Open Font License 1.1
 * (the LICENSE-*.txt files beside this one).
 */
${faces
  .map(
    (face) => `
@font-face {
  font-family: "${face.family}";
  font-style: normal;
  font-display: swap;
  font-weight: ${face.weight};
  src: url("./${face.file}") format("${face.format}");
  unicode-range: ${face.unicodeRange};
}`,
  )
  .join("\n")}
`;
writeFileSync(join(OUT, "fonts.css"), css);
console.log(`vendored ${faces.length} faces into ${OUT}`);
