/**
 * Run every candidate in Chromium and write `docs/measurements/stage2d-bench.md`.
 *
 *     bun run bench                       # build, then 3 runs per candidate, headed
 *     bun run.ts --runs 5 --only c,b      # after a build
 *     bun run.ts --headless               # CI; GPU paths differ, so numbers are not comparable
 *
 * Headed by default: on macOS the headed browser composites on the GPU like a real user's,
 * which is the machine PLAN L0-3 names. Each run is a fresh page, so one candidate's heap
 * and caches never leak into another's numbers. The median run (by frame p95) is reported,
 * with every run's p95 alongside so the spread is visible.
 */

import { spawnSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { cpus, platform, release, totalmem } from "node:os";
import { dirname, resolve } from "node:path";
import { parseArgs } from "node:util";

import { chromium } from "@playwright/test";
import { preview } from "vite";

import type { BenchResult } from "./src/main";
import { frameReport, type FrameReport } from "./src/trace";

type Run = BenchResult & { compositor: FrameReport | null };

const HERE = dirname(new URL(import.meta.url).pathname);
const OUT = resolve(HERE, "../../../docs/measurements/stage2d-bench.md");
const ALL = ["a", "a-batched", "b", "b-nocache", "c"];
/** Gate G6.1 (PLAN L6-1). */
const FRAME_P95_MS = 16.7;
const HIT_P95_MS = 2;

const { values } = parseArgs({
  options: {
    runs: { type: "string", default: "3" },
    only: { type: "string" },
    headless: { type: "boolean", default: false },
    out: { type: "string", default: OUT },
  },
});
const runs = Number(values.runs);
const ids = values.only ? values.only.split(",") : ALL;

const server = await preview({ root: HERE, preview: { port: 4179, strictPort: true }, logLevel: "warn" });
const base = server.resolvedUrls?.local[0] ?? "http://localhost:4179/";
const browser = await chromium.launch({ headless: values.headless });
const results: Record<string, Run[]> = {};
const CATEGORIES = ["cc", "viz", "benchmark", "blink.user_timing", "disabled-by-default-devtools.timeline.frame"];

try {
  for (const id of ids) {
    results[id] = [];
    for (let r = 0; r < runs; r++) {
      const page = await browser.newPage({ viewport: { width: 1600, height: 1000 }, deviceScaleFactor: 2 });
      await browser.startTracing(page, { categories: CATEGORIES });
      await page.goto(`${base}?candidate=${id}`);
      await page.waitForFunction(() => window.__bench !== undefined, undefined, { timeout: 180_000 });
      const result = await page.evaluate(() => window.__bench!);
      const trace = JSON.parse((await browser.stopTracing()).toString("utf8"));
      await page.close();
      if ("error" in result) throw new Error(`${id}: ${result.error}`);
      const compositor = frameReport(trace);
      results[id]!.push({ ...result, compositor });
      console.error(
        `${id} run ${r + 1}: presented p95 ${compositor?.presentedP95} ms, rAF p95 ${result.frame.p95} ms, hit p95 ${result.hit.p95} ms`,
      );
    }
  }
} finally {
  await browser.close();
  await new Promise<void>((done) => server.httpServer.close(() => done()));
}

/** What the user saw: the compositor's presented-frame interval, falling back to rAF if no trace. */
const frameP95 = (r: Run) => r.compositor?.presentedP95 ?? r.frame.p95;
const median = (list: Run[]) => [...list].sort((a, b) => frameP95(a) - frameP95(b))[Math.floor(list.length / 2)]!;
const sha = spawnSync("git", ["rev-parse", "--short=10", "HEAD"], { cwd: HERE, encoding: "utf8" }).stdout.trim();
const pass = (r: Run) => frameP95(r) <= FRAME_P95_MS && r.frame.p95 <= FRAME_P95_MS && r.hit.p95 <= HIT_P95_MS;

const lines: string[] = [];
lines.push("# Stage2D benchmark (L0-3)");
lines.push("");
lines.push("Generated by `bun run bench` in `tools/bench/stage2d` — see its README for the scene, workload and method.");
lines.push("");
lines.push("| | |");
lines.push("|---|---|");
lines.push(`| lab-ui commit | \`${sha}\` |`);
lines.push(`| Machine | ${cpus()[0]?.model ?? "?"}, ${cpus().length} cores, ${Math.round(totalmem() / 2 ** 30)} GB, ${platform()} ${release()} |`);
lines.push(`| Browser | Chromium ${browser.version()} (${values.headless ? "headless" : "headed"}) |`);
const any = Object.values(results)[0]?.[0];
if (any) lines.push(`| Viewport | ${any.viewport.width}×${any.viewport.height} CSS px @ ${any.devicePixelRatio}× |`);
lines.push(`| Runs | ${runs} per candidate, the median by presented-frame p95 reported |`);
lines.push("");
lines.push(
  `Gate **G6.1**: frame time p95 ≤ ${FRAME_P95_MS} ms during pan and zoom — both the interval between frames the compositor *presented* (what the user sees) and the main thread's rAF interval — and hit-test p95 ≤ ${HIT_P95_MS} ms.`,
);
lines.push("");
lines.push("| Candidate | Presented p95 (ms) | rAF p50 / p95 / p99 (ms) | Compositor frames: presented · partial · dropped · checkerboarded | Render work p95 (ms) | Hit-test p95 (ms) | Hit-test | Mount (ms) | JS heap (MB) | Presented p95 per run | G6.1 |");
lines.push("|---|---|---|---|---|---|---|---|---|---|---|");
for (const id of ids) {
  const list = results[id]!;
  const m = median(list);
  const c = m.compositor;
  const comp = c ? `${c.presented} · ${c.partial} · ${c.dropped} · ${c.checkerboarded} (of ${c.frames})` : "—";
  lines.push(
    `| ${m.label} | **${frameP95(m)}** | ${m.frame.p50} / ${m.frame.p95} / ${m.frame.p99} | ${comp} | ${m.work.p95} | **${m.hit.p95}** | ${m.hitTest} | ${m.mountMs} | ${m.heapMB ?? "—"} | ${list.map(frameP95).join(", ")} | ${pass(m) ? "pass" : "fail"} |`,
  );
}
lines.push("");
writeFileSync(values.out!, lines.join("\n"));
console.error(`wrote ${values.out}`);
